// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAyQq1-sH_1XxoUQNmysEQF846XDwJ3Xg',
    appId: '1:1098591719607:web:a0ddfefd7ad74735a03d32',
    messagingSenderId: '1098591719607',
    projectId: 'control-shizuya-weight',
    authDomain: 'control-shizuya-weight.firebaseapp.com',
    storageBucket: 'control-shizuya-weight.firebasestorage.app',
    measurementId: 'G-X0MR5VLYZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8PrvON1LxGYYgg2qfch62byBvtiu7oQ',
    appId: '1:1098591719607:android:fe6ac82353882f1ea03d32',
    messagingSenderId: '1098591719607',
    projectId: 'control-shizuya-weight',
    storageBucket: 'control-shizuya-weight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB799Yp_zl4GfYRd1R1Y0CUrsLaIxgJzTs',
    appId: '1:1098591719607:ios:824575b13b8750c3a03d32',
    messagingSenderId: '1098591719607',
    projectId: 'control-shizuya-weight',
    storageBucket: 'control-shizuya-weight.firebasestorage.app',
    iosBundleId: 'com.example.controlShizuyaWeightFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB799Yp_zl4GfYRd1R1Y0CUrsLaIxgJzTs',
    appId: '1:1098591719607:ios:824575b13b8750c3a03d32',
    messagingSenderId: '1098591719607',
    projectId: 'control-shizuya-weight',
    storageBucket: 'control-shizuya-weight.firebasestorage.app',
    iosBundleId: 'com.example.controlShizuyaWeightFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAyQq1-sH_1XxoUQNmysEQF846XDwJ3Xg',
    appId: '1:1098591719607:web:d07a4ee6169d8a0ba03d32',
    messagingSenderId: '1098591719607',
    projectId: 'control-shizuya-weight',
    authDomain: 'control-shizuya-weight.firebaseapp.com',
    storageBucket: 'control-shizuya-weight.firebasestorage.app',
    measurementId: 'G-XPN28P7N2E',
  );
}
